apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: liveness-probe
  name: liveness-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness-probe
  strategy: {}
  template:
    metadata:
      labels:
        app: liveness-probe
    spec:
      containers:
      - image: nginx:stable
        name: nginx
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
status: {}
