apiVersion: v1
kind: Pod
metadata:
  name: download-file
spec:
  initContainers:
  - name: init
    image: nginx
    command: ['sh', '-c', 'curl -o /output/dog.jpg https://github.com/JoseAngel1196/ckad-study-notes/blob/master/init_container/images/dog.jpg']
    volumeMounts:
    - name: shared
      mountPath: /output
  containers:
  - name: main
    image: busybox:stable
    command: ["sh", "-c", "while true; do ls /load/dog.jpg; done"]
    volumeMounts:
    - name: shared
      mountPath: /load
  volumes:
  - name: shared
    emptyDir: {}
