apiVersion: v1
kind: Pod
metadata:
  name: exercise1
spec:
  containers:
  - name: writer
    image: busybox:stable
    command: ['sh', '-c', 'echo "hello jose" > /output/data.txt; while true; do sleep 5; done']
    volumeMounts:
    - name: shared
      mountPath: /output
  - name: sidecar
    image: busybox:stable
    command: ["sh", "-c", "while true; do cat /input/data.txt; sleep 5; done"]
    volumeMounts:
    - name: shared
      mountPath: /input
  volumes:
  - name: shared
    emptyDir: {}
