apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ambassador-sidecar
  template:
    metadata:
      labels:
        app: ambassador-sidecar
    spec:
      containers:
      - name: main-container
        image: nginx
        ports:      
        - containerPort: 81
        volumeMounts:
        - name: nginx-main-config
          mountPath: /etc/nginx/conf.d
      - name: sidecar-container
        image: nginx
        ports:
         - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: default.conf   
            path: default.conf
      - name: nginx-main-config
        configMap:
          name: nginx-main-config
          items:
          - key: default.conf
            path: default.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://localhost:81;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-main-config
data:
  default.conf: |
    server {
      listen 81;
      listen [::]:81;
      server_name localhost;
      
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-sidecar
spec:
  selector:
    app: ambassador-sidecar
  ports:
  - name: http
    port: 80
    targetPort: 80
