apiVersion: batch/v1
kind: Job
metadata:
  name: error-job
spec:
  template:
    spec:
      containers:
      - image: busybox:stable
        name: error-job
        command: ["sleep", "10", ";", "exit", "1"]
      restartPolicy: OnFailure
